package com.example.m_agrilink.ui

import androidx.compose.runtime.Composable
import com.example.m_agrilink.data.AppLocale
import java.util.Locale

/**
 * English ↔ Kiswahili string table for every visible DashboardScreen string.
 * Missing Kiswahili entries fall back to English, so the toggle can never
 * render a blank. Other picker languages (Kikuyu, Kalenjin, Luo) also fall
 * back to English for now.
 */
private val EN = mapOf(
    "banner_title" to "National Market Analyzer",
    "banner_sub" to "Optimize your agricultural corridor trade margins live.",
    "tab_navigate" to "Navigate",
    "tab_language" to "Language",
    "tab_settings" to "Settings",
    "tab_articles" to "Articles",
    "nav_title" to "🌐 Navigate",
    "nav_home" to "🏠 Home Page Dashboard",
    "nav_market" to "📊 Market Overview",
    "nav_weather" to "🌦 Weather Terminal",
    "nav_articles" to "📰 AgriTech News & Articles",
    "nav_account" to "👨‍🌾 My Account",
    "dlg_close" to "Close",
    "dlg_cancel" to "Cancel",
    "lang_title" to "🔤 Language",
    "set_title" to "⚙️ System Settings",
    "set_dark_on" to "🌙 Dark Mode: On (tap to turn off)",
    "set_dark_off" to "☀️ Dark Mode: Off (tap to turn on)",
    "set_clear" to "🧹 Clear Device Cache",
    "set_a11y" to "♿ Accessibility Profiles",
    "set_cookies" to "🍪 Cookie Settings",
    "set_done" to "Done",
    "note_cache_cleared" to "Device cache cleared.",
    "note_a11y" to "Accessibility profiles: Standard / High-contrast / Large-text ready.",
    "back_home" to "← Back to Home Dashboard",
    "acct_title" to "👨‍🌾 Farmer Account",
    "acct_desc" to "Create an account to personalize advisories (%1\$s). Edit your profile anytime; link Gmail for one-tap login.",
    "acct_name_hint" to "Enter farmer name",
    "acct_create" to "Create Farmer Account",
    "err_name_empty" to "Enter your farmer name to create the account.",
    "err_create_failed" to "Could not create account: %1\$s",
    "acct_google" to "🔵 Continue with Google (Gmail)",
    "acct_cookie_line" to "🍪 Cookie settings: %1\$s — tap to review",
    "acct_locked1" to "🔒 Protected: your name and crops stay encrypted on this device (SQLCipher + Android Keystore). Only app code is on GitHub — local.properties and API keys are git-ignored and never committed.",
    "farm_title" to "👨‍🌾 My Farm — %1\$s%2\$s",
    "farm_google_tag" to " • 🔵 Google linked",
    "farm_meta" to "%1\$s • %2\$d saved crops • %3\$s",
    "farm_foryou" to "✨ For you: %1\$s",
    "farm_crops_btn" to "🌱 My Crops — enter & price them in Market",
    "farm_recent" to "Recent: %1\$s — tap Market for full details.",
    "farm_edit" to "Edit profile",
    "farm_link_google" to "Link Google",
    "farm_google_ok" to "Google ✓",
    "farm_signout" to "Sign out",
    "farm_delete" to "Delete my data",
    "farm_cookie_line" to "🍪 Cookies: %1\$s%2\$s — change",
    "farm_cookie_personal" to " • personalizing for you",
    "farm_cookie_generic" to " • not tracking",
    "acct_locked2" to "🔒 Protected: account data is encrypted on this device only (SQLCipher + Keystore). Signing out keeps data; Delete wipes it. Nothing personal is pushed to GitHub.",
    "cookie_title" to "🍪 We use cookies",
    "cookie_text" to "M-AgriLink stores on-device preferences (like cookies) to remember your county, crops and language — and, only if you Allow, to learn what you need so the Market, Weather and AI recommendations get better for you.",
    "cookie_sub" to "Choose Accept for the best personalization, or open Settings for granular control.",
    "cookie_accept" to "Accept",
    "cookie_settings_btn" to "Settings",
    "cookie_decline" to "Decline",
    "cookie_sheet_title" to "🍪 Cookie settings",
    "cr_analytics" to "Analytics",
    "cr_analytics_d" to "Anonymous usage counts to fix bugs.",
    "cr_personal" to "Personalization",
    "cr_personal_d" to "Learn my crops & areas to rank Market and AI tips for me.",
    "cr_offers" to "Offers",
    "cr_offers_d" to "Occasional relevant offers.",
    "cr_learn_on" to "📊 Learning: %1\$s",
    "cr_learn_on_empty" to "📊 Learning is on — your Market, Weather and AI use will personalize here.",
    "cr_learn_off" to "Tracking is off — recommendations stay generic.",
    "cr_save" to "Save choices",
    "ep_title" to "Edit profile",
    "ep_name" to "Display name",
    "ep_email" to "Email",
    "ep_phone" to "Phone",
    "ep_acre" to "Acreage",
    "ep_county_note" to "County is changed from the Home county picker.",
    "ep_err_name" to "Name cannot be empty.",
    "ep_err_email" to "Enter a valid email or leave it blank.",
    "ep_err_acre" to "Enter a valid acreage.",
    "ep_save" to "Save",
    "ep_save_fail" to "Save failed: %1\$s",
    "gl_title" to "🔵 Link Google account",
    "gl_text" to "Sign in with your Gmail to keep your farmer profile linked to Google on this device. No password leaves the phone — we store only the Gmail address.",
    "gl_email" to "Gmail address",
    "gl_email_hint" to "you@gmail.com",
    "gl_display" to "Display name (optional)",
    "gl_err" to "Enter a valid @gmail.com address.",
    "gl_save" to "Link Gmail",
    "gl_fail" to "Google link failed: %1\$s",
    "tip_prefix" to "☀️ Tip of the day: %1\$s",
    "tip_1" to "🌱 Scout leaf undersides twice a week — most pests hide there before spreading.",
    "tip_2" to "💧 Water early morning so leaves dry by noon and fungal spores can't settle.",
    "tip_3" to "🐛 Hang one pheromone trap per corner to catch outbreaks a week early.",
    "tip_4" to "💰 Sell the top-ranked Market page crop first — margins shift weekly.",
    "tip_5" to "📸 A sharp, sunlit leaf photo scans 3x more accurately than a dark one.",
    "tip_6" to "🌿 Mulch 5cm thick to lock moisture and starve weeds without chemicals.",
    "tip_7" to "📦 Dry grain to 13.5% before bagging — damp bags grow aflatoxin fast.",
    "vp_market" to "📊 Viewport: Market Overview • %1\$s",
    "vp_weather" to "🌦 Viewport: Weather Terminal • %1\$s",
    "vp_account" to "👨‍🌾 Viewport: My Account • %1\$s",
    "vp_articles" to "📰 Viewport: AgriTech News • %1\$s",
    "vp_home" to "🏠 Viewport: Home Dashboard • %1\$s",
    "mkt_hero" to "📊 M-AgriLink Market Terminal",
    "mkt_hero_all" to "All Kenya • pick a county",
    "mkt_hero_county" to "%1\$s County",
    "mkt_hero_tail" to " • Updated 2h ago • Retail + Wholesale",
    "mkt_county_hub" to "📍 County hub",
    "mkt_mycrops" to "🌱 My Crops — enter any crop of your choice",
    "mkt_crop_hint" to "e.g. Mango, Avocado, Coffee…",
    "mkt_add" to "Add",
    "mkt_tap_saved" to "Tap a saved crop for its full KAMIS trend & analysis below.",
    "mkt_filter" to "🌾 Crop filter",
    "mkt_all" to "All",
    "price_wholesale" to "Wholesale",
    "price_retail" to "Retail",
    "mkt_watching" to "⭐ Watching: %1\$s",
    "mkt_empty" to "Pick a county hub above (or on Home) to rank Maize, Beans, Onions and Sorghum by live corridor margin, trends, and per-market boards.",
    "alert_margin" to "🔔 Price alert: %1\$s margin is wide (+%2\$d%%). Aggregate and transport this week before the corridor tightens.",
    "best_deal" to "🏆 Best corridor deal: %1\$s — Local KES %2\$d → Hub KES %3\$d (net +KES %4\$d/bag). %5\$s.",
    "verdict_strong" to "STRONG SELL — wide margin, move fast",
    "verdict_fair" to "FAIR TRADE — worth the trip after costs",
    "verdict_thin" to "THIN MARGIN — bulk up or wait",
    "verdict_hold" to "HOLD — corridor loss after transit",
    "verdict_fmt" to "%1\$s (%2\$s%3\$d%%)",
    "verdict_honey" to "RISING TREND — 📈 +4.3% (+KES 40.00) (KAMIS honey index)",
    "row_local" to "Local KES %1\$d → Hub KES %2\$d (gross +KES %3\$d, transit KES 350)",
    "honey_row" to "Local KES %1\$d / Kg → Hub KES %2\$d / Kg (KAMIS honey index: base 970, wholesale 700)",
    "badge_rising" to "📈 +4.3% rising",
    "net_fmt" to "%1\$sKES %2\$d net",
    "row_source" to "Source: M-AgriLink offline corridor matrix (KALRO baseline), 47-county pricing engine.",
    "trend_title" to "📈 7-day wholesale trend — %1\$s (%2\$s)",
    "trend_hint" to "Tap bars read left→right: weekly low to today's hub price.",
    "trend_range" to "Week range: KES %1\$d → KES %2\$d.",
    "board_title" to "🏪 Per-market board — %1\$s (%2\$s, %3\$s)",
    "board_hint" to "Compare where to sell today; green = rising, red = falling.",
    "board_source" to "Source: M-AgriLink live board (KAMIS-inspired), simulated offline from corridor matrix.",
    "home_corridor" to "Target County Corridor Hub",
    "home_tap" to "Tap to select target region...",
    "home_dropdown" to "Dropdown Arrow",
    "home_crop_q" to "🌱 What Crop Have You Planted?",
    "home_crop_hint" to "Type Maize, Beans, Onions, Sorghum...",
    "home_corrected" to "🔍 Showing results for \"%1\$s\" (you typed \"%2\$s\")",
    "home_recent" to "⏱ My recent crops",
    "home_recent_hint" to "Tap a recent crop for full KAMIS trend & analysis.",
    "bp_title" to "📋 My Field Operation Blueprint",
    "bp_unmute" to "Unmute all audio",
    "bp_mute" to "Mute all audio",
    "lens_your_crop" to "your crop",
    "lens_foliar" to "foliar pest",
    "qual_dark" to "⚠️ Scanner Alert: Frame too dark — no crop detail visible. Clean the lens, turn on the light/flash, and point steady at the crop (leaf, fruit, or stem) filling the frame, then retry.",
    "qual_bright" to "⚠️ Scanner Alert: Frame washed out by glare. Shade the crop, wipe the lens, hold steady and retry.",
    "qual_blurry" to "⚠️ Scanner Alert: Blurry or covered lens — hold the phone steady, tap to focus, clean the lens, and make the crop fill the frame.",
    "qual_noleaf" to "⚠️ Scanner Alert: No crop detected. Point the camera at a crop leaf, fruit, or stem so it fills the frame — not a dark room, wall, or empty background.",
    "qual_lowconf" to "⚠️ Scanner Alert: Scan unclear (low confidence %1\$d%%). Clean the lens, improve lighting, move closer so the leaf fills the frame, and retry.",
    "qual_crash" to "⚠️ Scanner Alert: Leaf frame parsing failed due to suboptimal lighting conditions or hardware focus latency. Please steady your Lenovo camera device and try again.",
    "arb_title" to "Arbitrage Analysis Output",
    "arb_empty" to "Choose a destination trading hub above to dynamically calculate local vs cross-border profit margins, logistics costs, and regional advisory records.",
    "arb_route" to "Corridor Route: Baringo Local ➔ %1\$s",
    "arb_local" to "Local Price: KES %1\$d",
    "arb_hub" to "Hub Target Price",
    "arb_net" to "+KES %1\$d net",
    "arb_moist_fallback" to "Dry grain to 13.5% moisture ceiling before bagging.",
    "scan_title" to "🏥 Crop Disease Diagnostics",
    "scan_desc" to "Snap or upload any crop photo — leaf, fruit, or stem — for instant Google-AI control and management steps.",
    "scan_launch" to "Launch AI Camera Scanner",
    "scan_upload" to "🖼️ Upload Crop Image Instead",
    "scan_point" to "Point the lens at a %1\$s leaf or fruit…",
    "scan_crop_fallback" to "crop",
    "scan_no_image" to "⚠️ No image selected. Tap 🖼️ Upload Crop Image and pick a clear crop photo.",
    "scan_unreadable" to "⚠️ Scanner Alert: Could not read that image. Pick a clear crop leaf, fruit, or stem photo and try again.",
    "scan_decode_fail" to "⚠️ Scanner Alert: Could not read that image (%1\$s). Pick a clear crop leaf, fruit, or stem photo and try again.",
    "scan_frame_fail" to "⚠️ Scanner Alert: Leaf frame parsing failed due to suboptimal lighting conditions or hardware focus latency. Please steady your Lenovo camera device and try again.",
    "dlg_scanner" to "AI Field Camera Scanner",
    "scan_need_cam" to "Camera access is needed to scan crop leaves live in the field.",
    "scan_grant" to "Grant Camera Access",
    "scan_live_lens" to "📷 Live lens: %1\$s",
    "scan_conf" to "Confidence: %1\$d%% • %2\$s",
    "scan_upload_unclear" to "⚠️ Scanner Alert: That upload is unclear — pick a brighter, sharper crop photo (leaf, fruit, or stem filling the frame) or upload another image.",
    "scan_cam_unclear" to "⚠️ Scanner Alert: Scan unclear — clean the lens, improve lighting, point at a crop leaf or fruit filling the frame, and tap capture again.",
    "scan_status" to "📡 %1\$s • lens: %2\$s (%3\$d%%)",
    "scan_upload_another" to "🖼️ Upload another image",
    "scan_analyzing" to "🔍 AI Analyzer: Scanning crop leaves for anomalies...",
    "scan_analyzing_what" to "🔍 AI Analyzer: Scanning %1\$s for anomalies...",
    "scan_what_uploaded" to "uploaded image",
    "scan_what_leaves" to "crop leaves and fruits",
    "scan_tap_capture" to "Tap the capture circle to scan %1\$s leaves with the back camera.",
    "scan_cam_fail" to "⚠️ Camera failed to start (%1\$s). Grant camera permission, upload an image instead, or restart the scanner.",
    "google_title" to "🔎 Google AI Crop Details",
    "google_src" to "Source: %1\$s • any crop part (leaf, fruit, stem)",
    "google_pulling" to "Pulling Google AI details…",
    "google_empty" to "Google details will appear here when online.",
    "google_open" to "🔍 Open Full Details on Google",
    "google_fail" to "Google lookup failed. Check connection and use the buttons below.",
    "btn_youtube" to "▶️ YouTube",
    "btn_facebook" to "📘 Facebook",
    "btn_cabi" to "View full advisory profile on CABI Plantwise Bank",
    "src_gallery" to "Gallery upload",
    "scan_uploaded_img" to "Uploaded crop image",
    "scan_capture" to "Capture leaf scan",
    "scan_close" to "Close Scan",
    "scan_full_prefix" to "Live lens match (%1\$s): %2\$s (%3\$d%% confidence via %4\$s).",
    "scan_full_google" to "🔎 Google AI (%1\$s): %2\$s",
    "wx_rain_badge" to "🌧️ Active Rainfall Detected at your GPS Location.",
    "wx_rain_advisory" to "☔ Field Advisory: Active rain showers confirmed over your plot. Immediately suspend all open fertilizer spraying or pesticide applications to avoid direct crop washouts.",
    "pay_title" to "🔒 M-Pesa Payment",
    "pay_mpesa" to "💳 Pay via M-Pesa Securely",
    "pay_sending" to "Sending secure M-Pesa prompt…",
    "pay_success" to "✅ STK push sent to %1\$s for %2\$s. Enter your M-Pesa PIN on your phone to complete.",
    "pay_failed" to "❌ Payment failed: %1\$s",
    "pay_noconfig" to "Payment not configured — ask the app owner to add Daraja credentials to local.properties, then rebuild.",
    "pay_badphone" to "Add a valid M-Pesa phone number (07…/01…) in your Account profile first.",
    "pay_err_timeout" to "Request timed out. Try again.",
    "pay_err_offline" to "No internet connection. Reconnect and try again.",
    "pay_err_rejected" to "Payment rejected by Safaricom (%1\$s).",
    "logi_bags" to "Bags to transport",
    "logi_bags_hint" to "e.g. 10",
    "logi_estimate" to "Estimated transit: %1\$s (%2\$d bags × KES %3\$d).",
    "faq_title" to "❓ Frequently Asked Questions",
    "faq_q1" to "📱 Will M-AgriLink work when my phone is completely offline?",
    "faq_a1" to "Yes! M-AgriLink features an built-in offline shield. Your 47 Kenyan county market values, weather forecasts, and Shamba AI agronomic guidelines are saved straight to your phone's memory via our secure Room Database.",
    "faq_q2" to "🐛 How accurate is the Shamba AI Crop Scanner?",
    "faq_a2" to "The AI Scanner utilizes multi-source frameworks backed by official KALRO ABIRI, CABI Plantwise, and icipe databases. It matches physical leaf windowpane anomalies against verified biological and chemical mitigation structures.",
    "faq_q3" to "🗺️ Why does the app ask for my location permission?",
    "faq_a3" to "We use your phone's native GPS coordinates solely to query the keyless Open-Meteo REST API to give you hyper-localized, real-time temperatures and localized rain alerts for your specific field.",
    "faq_q4" to "🐝 What is the KALRO ABIRI Hive Journal?",
    "faq_a4" to "It is an advanced apiculture tracker built under your platform creator profile Levis Lekesio. It guides you step-by-step through modern Langstroth colony forage cycles, moisture thresholds, and honey yield optimization.",
    "scan_confirm_unclear" to "⚠️ Scan unclear — no valid crop captured. Clean the lens, improve lighting, point at a crop leaf, fruit, or stem filling the frame, and launch the scanner again.",
    "src_camera" to "Camera live",
    "shamba_title" to "💬 Ask Shamba AI",
    "shamba_desc" to "Type how your farm, crops or cattle are behaving — Shamba replies with friendly advice in English or Kiswahili.",
    "shamba_start" to "Start Chat",
    "lorry_title" to "🚚 Lorry Logistics Finder",
    "lorry_demo" to "Demo directory — tap Call or WhatsApp to book:",
    "lorry_hide" to "Hide Transporter Contacts",
    "lorry_find" to "Find Lorry Now",
    "lorry_tasks" to "🧾 My transport tasks — track your lorry:",
    "lorry_enroute" to "🚚 Mark En Route",
    "lorry_delivered" to "✅ Mark Delivered",
    "lorry_registered" to "✓ Driver-registered lorries:",
    "lorry_call" to "📞 Call",
    "lorry_wa" to "💬 WhatsApp",
    "lorry_hire" to "🚜 Hire",
    "lorry_close_reg" to "Close lorry registration",
    "lorry_open_reg" to "＋ Register my lorry (driver)",
    "lorry_save" to "Save lorry",
    "lorry_hint_name" to "Driver / SACCO name",
    "lorry_hint_phone" to "Phone e.g. 0722000000",
    "lorry_hint_capacity" to "Capacity e.g. 10T",
    "lorry_hint_town" to "Base town e.g. Marigat",
    "lorry_hint_route" to "Route e.g. Marigat → Nairobi Hub",
    "sac3_title" to "💰 SACCO Input Planner",
    "sac3_sub_empty" to "Wholesale seed & fertilizer trends (Baringo baseline).",
    "sac3_sub_county" to "Wholesale trends for %1\$s — budget before planting.",
    "sac3_tip" to "Micro-saving tip: Save KES 250/week via SACCO to cover 1 acre DAP + seed before rains.",
    "cta_launch" to "Launch Regional Corridor Analyzer",
    "bp_action" to "🚜 Immediate Action:",
    "bp_harvest" to "🌾 Safe Harvesting Marker:",
    "live_mgmt" to "⚠️ Live Crop Management Advisory",
    "live_brief_title" to "🌐 Live Crop Brief: %1\$s",
    "live_searching" to "Searching live sources…",
    "live_none" to "No blueprint found for \"%1\$s\" — try Maize, Beans, Onions or Sorghum.",
    "live_saved" to "Auto-saved to My recent crops on this device.",
    "adv_maize_humid" to "High humidity alert (72%) detected across Baringo. Field conditions increase the risk of Gray Leaf Spot fungal strains. Monitor crop leaves closely this week.",
    "adv_beans_calm" to "Winds are calm at 5.2 km/h. Ideal morning window open to apply safe crop protections safely.",
    "adv_default" to "Temp %1\$s°C • Humidity %2\$d%% • Wind %3\$s km/h — scout %4\$s fields early morning; keep foliage dry to curb fungal pressure.",
    "read_aloud" to "Read scan result aloud",
    "scan_ident" to "🩺 PEST IDENTIFICATION",
    "scan_ident_healthy" to "Your %1\$s looks healthy (%2\$d%% confidence via %3\$s).",
    "scan_ident_hit" to "Your crop is facing an active infestation of %1\$s on %2\$s (%3\$d%% confidence via %4\$s).",
    "scan_control" to "🛠️ IMMEDIATE CONTROL & MANAGEMENT",
    "scan_protocol" to "🌿 CROP-SPECIFIC PROTOCOL",
    "scan_validated" to "✅ VALIDATED CONTROL (KALRO • CABI • icipe • FAO)",
    "honey_live" to "🍯 LIVE MARKET FEED • KAMIS",
    "honey_deviations" to "📍 LOCALIZED MARKET DEVIATIONS",
    "honey_base" to "Base Market Index Average: %1\$s",
    "honey_traj" to "Trajectory Vector: %1\$s",
    "logi_title" to "🚚 Regional Transport & Lorry Logistics",
    "logi_nocounty" to "Select a corridor hub above for tonight's departures.",
    "logi_route" to "Live corridor: %1\$s ➔ %2\$s",
    "logi_contact" to "📞 Tap to contact driver",
    "logi_line1" to "• %1\$d Verified Transporters available near %2\$s heading to %3\$s tonight.",
    "logi_line2" to "• Estimated Transit Cost: KES %1\$d - KES %2\$d per bag of grain/produce.",
    "logi_line3" to "• Security Status: %1\$s Tap to contact driver.",
    "sac_title" to "💰 SACCO Certified Input Planner",
    "sac_sub" to "Certified wholesale trends — budget before planting, avoid price gouging.",
    "sac_acre" to "Estimated acreage",
    "sac_acre_hint" to "e.g. 2.5",
    "sac_proj_for" to "Baseline projection for %1\$s acre(s):",
    "sac_seed" to "🌱 Seed (%1\$d pkts): %2\$s",
    "sac_dap" to "🧪 DAP (%1\$d bags): %2\$s",
    "sac_compost" to "🌿 Compost (%1\$d bags): %2\$s",
    "sac_total" to "Total investment: %1\$s",
    "hive_title" to "🐝 KALRO ABIRI Hive Journal",
    "hive_yield_h" to "📊 Projected Yield Metrics (Modern Langstroth / KTB Hives)",
    "hive_yield_1" to "• Target Yield: 24kg to 30kg of raw honey per hive, harvested twice annually.",
    "hive_yield_2" to "• Subsidized Hive Investment: KES 2,500 standard unit entry cost.",
    "hive_yield_3" to "• Profit Profile: 10 active hives yield approx. KES 144,000 per season.",
    "hive_forage_h" to "🌱 Regional Honey Forage & Floral Calendar",
    "hive_forage_1" to "• Forage Cover: Acacia and multi-flower shrub preservation in ASAL corridors.",
    "hive_forage_2" to "• Climate Shield: Maintain internal hive temperature under extreme drought to prevent absconding or colony migration.",
    "hive_gallery_h" to "📸 Apiary Reference Gallery",
    "hive_footnote" to "*Sourced via KALRO Apiculture Value Chain, Climate-Smart TIMPs Manual 2020.*",
    "art_hero" to "📰 AgriTech & Agriculture News",
    "art_sub" to "Top & trending stories for Kenyan farmers.",
    "art_refresh" to "↻ Refresh stories",
    "art_live" to "📡 LIVE",
    "art_offline" to "📦 OFFLINE PICKS",
    "art_loading" to "Fetching top agritech stories…",
    "art_read" to "📖 Read story",
    "art_video" to "▶️ Video",
    "art_sources" to "Sources: Google News RSS (live) • FAO / icipe / CABI / KALRO (offline picks).",
    "out_empty" to "Select a county to unlock live corridor margins, best-crop ranking, and sell/hold signals.",
    "out_main" to "Corridor pulse for %1\$s: %2\$d crops tracked. Best margin: %3\$s (+KES %4\$d net). Average net across crops: %5\$sKES %6\$d/bag after KES 350 transit. %7\$s",
    "out_good" to "Market favors sellers — aggregate and transport this week.",
    "out_tight" to "Market is tight — sell only the top-ranked crop or bulk with neighbours.",
    "out_your_county" to "your county",
    "honey_name" to "🐝 Pure Natural Honey",
    "honey_bulk_lead" to "Wholesale Bulking:",
    "honey_corr_lead" to "Renowned Production Corridors:",
    "honey_base_val" to "KES 970.00 / Kilogram",
    "honey_traj_val" to "📈 +4.3% (+KES 40.00) Rising Trend",
    "honey_bulk_val" to "KES 700.00 / Kg (20L/25L Bulk Containers)",
    "honey_corr_val" to "KES 750.00 – KES 850.00 / 1Kg Jar (Baringo Koriema Packers & Makueni Acacia metrics)",
    "honey_footnote" to "*Sourced from the official Kenya Agricultural Market Information System (KAMIS) Regional Portal.*",
    "trans_empty" to "3 Transporters near Marigat available for transit to Nairobi Hub",
    "trans_fmt" to "%1\$d Transporters near %2\$s available for transit to Nairobi Hub from KES %3\$d/ton",
    "lorry_you" to "your location",
    "lorry_security" to "Active corridors clear.",
    "input_maize" to "Maize Seed (2kg)",
    "input_dap" to "DAP Fertilizer (50kg)",
    "input_can" to "CAN Top-dress (50kg)",
    "unit_pack2kg" to "2kg pack",
    "unit_bag50kg" to "50kg bag",
    "sac_item_dap" to "Certified DAP Fertilizer",
    "sac_item_dap_spec" to "50Kg Bag",
    "sac_item_dap_badge" to "SACCO Standard Subsidized",
    "sac_item_seed" to "Certified Maize Seed",
    "sac_item_seed_spec" to "2Kg Packet - H614",
    "sac_item_compost" to "Organic Compost / Bio-fertilizer",
    "sac_item_compost_spec" to "50Kg Bag",
    "rem_cat_cultural" to "💡 Cultural Remedy",
    "rem_cat_eco" to "🌱 Ecological Strategy",
    "rem_cat_chem" to "🧪 Safe Chemical Action",
    "rem_mango_cultural" to "Hang methyl eugenol pheromone traps at canopy level (10 per acre). Collect and bury fallen fruits 2 feet deep or seal in black plastic bags under sun to suffocate larvae. Handpick and crush visible egg masses twice a week to disrupt lifecycle progression.",
    "rem_mango_eco" to "Implement the Push-Pull methodology by intercropping with Desmodium to repel moths naturally. Keep orchard floor clean and conserve weaver ants as natural fruit-fly predators.",
    "rem_mango_chem" to "If infestation tracking exceeds a strict 20% plot threshold, apply registered spot-treatments like Emamectin Benzoate directly into the crop whorl. Do not spray heavily near harvest.",
    "rem_beans_cultural" to "Earth up soil around stems during weeding to grow adventitious roots. Handpick and crush visible egg masses twice a week to disrupt lifecycle progression.",
    "rem_beans_eco" to "Implement the Push-Pull methodology by intercropping with Desmodium to repel moths naturally. Spray neem seed kernel extract or potassium-soap early morning before bees are active.",
    "rem_beans_chem" to "If infestation tracking exceeds a strict 20% plot threshold, apply registered spot-treatments like Emamectin Benzoate directly into the crop whorl.",
    "rem_maize_cultural" to "Handpick and crush visible egg masses twice a week to disrupt lifecycle progression. Scout whorls twice weekly and crush caterpillars directly in the funnel.",
    "rem_maize_eco" to "Implement the Push-Pull methodology by intercropping with Desmodium to repel moths naturally. Plant Napier/Brachiaria trap borders to cut pressure over 70%.",
    "rem_maize_chem" to "If infestation tracking exceeds a strict 20% plot threshold, apply registered spot-treatments like Emamectin Benzoate directly into the crop whorl. Alternate chemical classes to block resistance.",
    "rem_general_cultural" to "Prune infected lower leaves immediately and destroy by burning. Handpick and crush visible egg masses twice a week to disrupt lifecycle progression.",
    "rem_general_eco" to "Implement the Push-Pull methodology by intercropping with Desmodium to repel moths naturally. Space rows for airflow and avoid overhead evening irrigation.",
    "rem_general_chem" to "If infestation tracking exceeds a strict 20% plot threshold, apply registered spot-treatments like Emamectin Benzoate directly into the crop whorl.",
    "adv_moisture" to "13.5% safe harvest moisture ceiling (KALRO). Dry grain to ≤13.5% before bagging to prevent aflatoxin/mould.",
    "adv_maize_land" to "KALRO Land Prep (Maize): Deep plough 20-25cm at onset of rains, harrow to fine tilth. Apply 10t/ha well-decomposed manure + 60kg DAP/ha at planting.",
    "adv_maize_space" to "Planting Spacing (Maize): 75cm x 25cm, 1 seed per hole (approx. 53,000 plants/ha). Thin to 1 vigorous seedling.",
    "adv_maize_harvest" to "Harvest when husks turn brown and kernels are hard. Shell and dry on tarpaulin to 13.5% moisture before storage in hermetic bags.",
    "adv_beans_land" to "KALRO Land Prep (Beans): Plough 15-20cm, fine firm seedbed. Inoculate seed with rhizobium. Apply 40kg TSP/ha at planting; avoid excess nitrogen.",
    "adv_beans_space" to "Planting Spacing (Beans): 45cm x 10cm, 1 seed per hole (approx. 220,000 plants/ha). Plant 3-5cm deep.",
    "adv_beans_harvest" to "Harvest when 90% pods are dry/yellow. Thresh promptly and dry beans to 13.5% moisture ceiling before bagging.",
    "adv_onions_land" to "KALRO Land Prep (Onions): Raise nursery bed 1m wide, well-drained loam pH 6.0-7.0. Transplant 6-8 week seedlings to deeply ploughed (20cm), level field with 8t/ha manure.",
    "adv_onions_space" to "Planting Spacing (Onions): 30cm x 10cm in field (approx. 330,000 plants/ha). Mulch and irrigate lightly twice weekly.",
    "adv_onions_harvest" to "Harvest when 70% tops fall over. Cure bulbs 7-10 days in shade to outer-scale dryness (equivalent to ≤13.5% seed/grain handling standard) before grading.",
    "adv_sorghum_land" to "KALRO Land Prep (Sorghum): Minimum tillage / plough 15-20cm. Drought-tolerant; apply 40kg CAN/ha as top-dress at knee-height. Control striga by rotation with legumes.",
    "adv_sorghum_space" to "Planting Spacing (Sorghum): 75cm x 20cm, 2 seeds per hole thinned to 1 (approx. 66,000 plants/ha).",
    "adv_sorghum_harvest" to "Harvest panicles when grain is hard and <13.5% moisture. Thresh, winnow and dry further to 13.5% ceiling for safe storage.",
    "adv_custom_land" to "KALRO Land Prep (%1\$s): Prepare a deep, well-drained seedbed at onset of rains. Apply well-decomposed manure + basal fertilizer per soil test.",
    "adv_custom_space" to "Planting Spacing (%1\$s): Space for full canopy airflow per KALRO row guide; mulch to hold moisture.",
    "adv_custom_harvest" to "Harvest %1\$s at full maturity and dry/cure to the 13.5% safe handling ceiling before storage or sale.",
    "cb_lead_1" to "Physical Removal:",
    "cb_rest_1" to "Clear the pest manually with a strong jet of water and handpick visible egg masses twice weekly.",
    "cb_lead_2" to "Pruning & Sanitation:",
    "cb_rest_2" to "Safely remove and destroy overrun plant tissue by pruning infected leaves and burning them to break the lifecycle.",
    "cb_lead_3" to "Organic Sprays:",
    "cb_rest_3" to "Apply neem-based or bio-rational morning spraying protocols, coating branches with neem oil or insecticidal soap in cool hours.",
    "cb_lead_4" to "Biological Control:",
    "cb_rest_4" to "Use predator cards and habitat management — conserve natural enemies, keep Desmodium intercrop and trap borders to suppress pressure.",
    "overview_cta" to "💡 Let's optimize: Are you growing these crops in a small home garden plot or a large-scale commercial orchard? Let Shamba Al know so we can suggest tailored systemic organic treatment blends matching your growing scale!",
    "overview_sources" to "*Verified via KALRO ASAL Research Databases, CABI Plantwise Knowledge Bank, and icipe Kenya.*",
    "diag_healthy_title" to "✅ DIAGNOSIS: %1\$s looks healthy (%2\$d%% confidence via %3\$s).",
    "diag_mango" to "🎯 DIAGNOSIS: Mango Fruit Fly (Bactrocera dorsalis) damage detected on skin surfaces.",
    "diag_beans" to "🎯 DIAGNOSIS: Bean Fly (Ophiomyia phaseoli) stem tunneling or Black Bean Aphid clustering detected.",
    "diag_maize" to "🎯 DIAGNOSIS: %1\$s detected (%2\$d%% confidence via %3\$s) — Fall Armyworm (Spodoptera frugiperda) protocol.",
    "diag_general" to "🎯 DIAGNOSIS: General foliar anomaly detected.",
    "diag_general_crop" to "🎯 DIAGNOSIS: General Foliar/Leaf spot anomaly detected for %1\$s",
    "body_preventive" to "🌿 PREVENTIVE CARE: Keep scouting twice weekly, clear weeds and debris around the base, mulch to hold moisture, and watch leaf edges after humid nights. Retake the scan if spots, holes, or yellowing appear.",
    "body_mango" to "🌿 MANAGEMENT ADVISORY: Do not apply heavy chemical sprays near harvesting. Hang localized methyl eugenol pheromone traps at canopy level (10 traps per acre) to trap male flies. Collect and bury all fallen fruits at least 2 feet deep or seal them inside black plastic bags under the sun for few days to completely suffocate larvae and break the pest's lifecycle.",
    "body_beans" to "🌿 MANAGEMENT ADVISORY: Earth up soil around the plant stems during weeding to encourage adventitious root growth. For severe aphid attacks, spray natural neem seed kernel extracts or potassium-soap solutions early in the morning before bees become active.",
    "body_maize_1" to "🌿 PUSH-PULL BIOLOGICAL STRATEGY (icipe Kenya): Intercrop your maize rows cleanly with Desmodium (repels the moths away via chemical volatilization) and plant Napier Grass or Brachiaria along your field perimeters as an attractive trap crop. This method cuts pest pressure by over 70% naturally.",
    "body_maize_2" to "🐛 SCOUTING & CULTURAL REMEDIES (CABI Plantwise): Perform structural field scouting twice a week. Handpick and destroy visible egg masses or caterpillars immediately. Crushing caterpillars against leaf whorls prevents secondary lifecycle generations.",
    "body_maize_3" to "🧪 TIMED CHEMICAL EMERGENCY ACTION (CIMMYT & FAO): If leaf damage indices surpass a 20% infestation threshold across young stalks, apply targeted bio-rationals or registered chemical options such as Spinetoram or Spinosad directly down into the whorls. Alternate chemical classes to completely halt pest resistance build-up.",
    "body_general" to "🌿 MANAGEMENT ADVISORY: Maintain proper plant row spacing to improve air circulation and reduce leaf wetness. Prune infected lower leaves immediately. Avoid overhead irrigation during cold evenings to limit fungal spore tracking across your plot."
)

private val SW = mapOf(
    "banner_title" to "Kichambuzi cha Soko la Kitaifa",
    "banner_sub" to "Boresha biashara yako ya mazao moja kwa moja.",
    "tab_navigate" to "Enda",
    "tab_language" to "Lugha",
    "tab_settings" to "Mipangilio",
    "tab_articles" to "Makala",
    "nav_title" to "🌐 Enda",
    "nav_home" to "🏠 Dashibodi ya Nyumbani",
    "nav_market" to "📊 Muhtasari wa Soko",
    "nav_weather" to "🌦 Hali ya Hewa",
    "nav_articles" to "📰 Habari za AgriTech",
    "nav_account" to "👨‍🌾 Akaunti Yangu",
    "dlg_close" to "Funga",
    "dlg_cancel" to "Ghairi",
    "lang_title" to "🔤 Lugha",
    "set_title" to "⚙️ Mipangilio ya Mfumo",
    "set_dark_on" to "🌙 Modi ya Giza: Imewashwa (gusa kuzima)",
    "set_dark_off" to "☀️ Modi ya Giza: Imezimwa (gusa kuwasha)",
    "set_clear" to "🧹 Futa Akiba ya Kifaa",
    "set_a11y" to "♿ Mipangilio ya Upatikanaji",
    "set_cookies" to "🍪 Mipangilio ya Vidakuzi",
    "set_done" to "Sawa",
    "note_cache_cleared" to "Akiba ya kifaa imefutwa.",
    "note_a11y" to "Wasifu wa upatikanaji: Kawaida / Tofauti-kubwa / Herufi-kubwa ziko tayari.",
    "back_home" to "← Rudi Dashibodi ya Nyumbani",
    "acct_title" to "👨‍🌾 Akaunti ya Mkulima",
    "acct_desc" to "Fungua akaunti ili ushauri uboreshwe (%1\$s). Hariri wasifu wako wakati wowote; unganisha Gmail kwa kuingia mara moja.",
    "acct_name_hint" to "Andika jina la mkulima",
    "acct_create" to "Fungua Akaunti ya Mkulima",
    "err_name_empty" to "Andika jina lako la mkulima ili kufungua akaunti.",
    "err_create_failed" to "Imeshindwa kufungua akaunti: %1\$s",
    "acct_google" to "🔵 Endelea na Google (Gmail)",
    "acct_cookie_line" to "🍪 Mipangilio ya vidakuzi: %1\$s — gusa kukagua",
    "acct_locked1" to "🔒 Imelindwa: jina lako na mazao yako hubaki kwa usalama kwenye kifaa hiki (SQLCipher + Android Keystore). Ni msimbo wa programu tu ulio kwenye GitHub — local.properties na funguo za API hazihifadhiwi humo.",
    "farm_title" to "👨‍🌾 Shamba Langu — %1\$s%2\$s",
    "farm_google_tag" to " • 🔵 Google imeunganishwa",
    "farm_meta" to "%1\$s • mazao %2\$d yaliyohifadhiwa • %3\$s",
    "farm_foryou" to "✨ Kwa ajili yako: %1\$s",
    "farm_crops_btn" to "🌱 Mazao Yangu — andika na uyaweke bei Sokoni",
    "farm_recent" to "Hivi karibuni: %1\$s — gusa Soko kwa maelezo kamili.",
    "farm_edit" to "Hariri wasifu",
    "farm_link_google" to "Unganisha Google",
    "farm_google_ok" to "Google ✓",
    "farm_signout" to "Toka",
    "farm_delete" to "Futa data zangu",
    "farm_cookie_line" to "🍪 Vidakuzi: %1\$s%2\$s — badilisha",
    "farm_cookie_personal" to " • inajifunza kwa ajili yako",
    "farm_cookie_generic" to " • haifuatilii",
    "acct_locked2" to "🔒 Imelindwa: data ya akaunti imesimbwa kwenye kifaa hiki pekee (SQLCipher + Keystore). Kutoka huhifadhi data; Kufuta huifuta. Hakuna chochote cha kibinafsi kinachotumwa GitHub.",
    "cookie_title" to "🍪 Tunatumia vidakuzi",
    "cookie_text" to "M-AgriLink huhifadhi mapendeleo kwenye kifaa (kama vidakuzi) kukumbuka kaunti, mazao na lugha yako — na, ukikubali tu, kujifunza unachohitaji ili mapendekezo ya Soko, Hali ya Hewa na AI yawe bora kwako.",
    "cookie_sub" to "Chagua Kubali kwa uboreshaji bora, au fungua Mipangilio kwa udhibiti wa kina.",
    "cookie_accept" to "Kubali",
    "cookie_settings_btn" to "Mipangilio",
    "cookie_decline" to "Kataa",
    "cookie_sheet_title" to "🍪 Mipangilio ya vidakuzi",
    "cr_analytics" to "Takwimu",
    "cr_analytics_d" to "Hesabu za matumizi zisizojulikana kurekebisha hitilafu.",
    "cr_personal" to "Uboreshaji",
    "cr_personal_d" to "Jifunze mazao na maeneo yangu ili kupanga Soko na vidokezo vya AI kwa ajili yangu.",
    "cr_offers" to "Matoleo",
    "cr_offers_d" to "Matoleo muhimu mara kwa mara.",
    "cr_learn_on" to "📊 Inajifunza: %1\$s",
    "cr_learn_on_empty" to "📊 Kujifunza kumewashwa — matumizi yako ya Soko, Hali ya Hewa na AI yatajiboresha hapa.",
    "cr_learn_off" to "Ufuatiliaji umezimwa — mapendekezo hubaki ya kawaida.",
    "cr_save" to "Hifadhi machaguo",
    "ep_title" to "Hariri wasifu",
    "ep_name" to "Jina la kuonyesha",
    "ep_email" to "Barua pepe",
    "ep_phone" to "Simu",
    "ep_acre" to "Ukubwa wa shamba (ekari)",
    "ep_county_note" to "Kaunti hubadilishwa kutoka kichagua kaunti cha Nyumbani.",
    "ep_err_name" to "Jina haliwezi kuwa tupu.",
    "ep_err_email" to "Andika barua pepe sahihi au acha tupu.",
    "ep_err_acre" to "Andika ukubwa sahihi wa shamba.",
    "ep_save" to "Hifadhi",
    "ep_save_fail" to "Imeshindwa kuhifadhi: %1\$s",
    "gl_title" to "🔵 Unganisha akaunti ya Google",
    "gl_text" to "Ingia na Gmail yako ili wasifu wako uunganishwe na Google kwenye kifaa hiki. Hakuna nenosiri linalotoka simuni — tunahifadhi anwani ya Gmail pekee.",
    "gl_email" to "Anwani ya Gmail",
    "gl_email_hint" to "wewe@gmail.com",
    "gl_display" to "Jina la kuonyesha (hiari)",
    "gl_err" to "Andika anwani sahihi ya @gmail.com.",
    "gl_save" to "Unganisha Gmail",
    "gl_fail" to "Imeshindwa kuunganisha Google: %1\$s",
    "tip_prefix" to "☀️ Kidokezo cha leo: %1\$s",
    "tip_1" to "🌱 Chunguza chini ya majani mara mbili kwa wiki — wadudu wengi hujificha huko kabla ya kuenea.",
    "tip_2" to "💧 Mwagilia asubuhi na mapema ili majani yakauke kabla ya adhuhuri na fangasi wasishike.",
    "tip_3" to "🐛 Tundika mtego mmoja wa feromoni kila kona ili kugundua milipuko wiki moja mapema.",
    "tip_4" to "💰 Uza zao lililoongoza kwenye ukurasa wa Soko kwanza — faida hubadilika kila wiki.",
    "tip_5" to "📸 Picha kali ya jani kwenye jua huchanganuliwa mara 3 vizuri zaidi kuliko picha nyeusi.",
    "tip_6" to "🌿 Tandaza matandazo unene wa sm 5 kufunga unyevu na kunyonga magugu bila kemikali.",
    "tip_7" to "📦 Kausha nafaka hadi 13.5% kabla ya kufunga — magunia mabichi huotesha sumu ya aflatoxin haraka.",
    "vp_market" to "📊 Ukiwa: Muhtasari wa Soko • %1\$s",
    "vp_weather" to "🌦 Ukiwa: Hali ya Hewa • %1\$s",
    "vp_account" to "👨‍🌾 Ukiwa: Akaunti Yangu • %1\$s",
    "vp_articles" to "📰 Ukiwa: Habari za AgriTech • %1\$s",
    "vp_home" to "🏠 Ukiwa: Dashibodi ya Nyumbani • %1\$s",
    "mkt_hero" to "📊 Kituo cha Soko cha M-AgriLink",
    "mkt_hero_all" to "Kenya nzima • chagua kaunti",
    "mkt_hero_county" to "Kaunti ya %1\$s",
    "mkt_hero_tail" to " • Ilisasishwa saa 2 zilizopita • Rejareja + Jumla",
    "mkt_county_hub" to "📍 Kitovu cha kaunti",
    "mkt_mycrops" to "🌱 Mazao Yangu — andika zao lolote upendalo",
    "mkt_crop_hint" to "k.m. Maembe, Parachichi, Kahawa…",
    "mkt_add" to "Ongeza",
    "mkt_tap_saved" to "Gusa zao lililohifadhiwa kwa mwenendo kamili wa KAMIS na uchambuzi hapa chini.",
    "mkt_filter" to "🌾 Kichujio cha mazao",
    "mkt_all" to "Yote",
    "price_wholesale" to "Jumla",
    "price_retail" to "Rejareja",
    "mkt_watching" to "⭐ Ninafuatilia: %1\$s",
    "mkt_empty" to "Chagua kitovu cha kaunti hapo juu (au Nyumbani) ili kupanga Mahindi, Maharagwe, Vitunguu na Mtama kwa faida, mwenendo na mbao za masoko.",
    "alert_margin" to "🔔 Tahadhari ya bei: faida ya %1\$s ni kubwa (+%2\$d%%). Kusanya na usafirishe wiki hii kabla soko halijabana.",
    "best_deal" to "🏆 Dilisha bora: %1\$s — Nyumbani KES %2\$d → Kitovuni KES %3\$d (faida +KES %4\$d/gunia). %5\$s.",
    "verdict_strong" to "UZA KWA NGUVU — faida kubwa, songa haraka",
    "verdict_fair" to "BIASHARA YA HAKI — inafaa baada ya gharama",
    "verdict_thin" to "FAIDA NDOGO — kusanya kwa wingi au subiri",
    "verdict_hold" to "SUBIRI — hasara baada ya usafiri",
    "verdict_fmt" to "%1\$s (%2\$s%3\$d%%)",
    "verdict_honey" to "MWELEKEO UNAOPANDA — 📈 +4.3% (+KES 40.00) (fahirisi ya asali KAMIS)",
    "row_local" to "Nyumbani KES %1\$d → Kitovuni KES %2\$d (jumla +KES %3\$d, usafiri KES 350)",
    "honey_row" to "Nyumbani KES %1\$d / Kg → Kitovuni KES %2\$d / Kg (fahirisi ya asali KAMIS: msingi 970, jumla 700)",
    "badge_rising" to "📈 +4.3% inapanda",
    "net_fmt" to "%1\$sKES %2\$d faida",
    "row_source" to "Chanzo: M-AgriLink nje ya mtandao (msingi wa KALRO), injini ya bei ya kaunti 47.",
    "trend_title" to "📈 Mwenendo wa siku 7 — %1\$s (%2\$s)",
    "trend_hint" to "Gusa pau soma kushoto→kulia: bei ya chini ya wiki hadi bei ya leo kitovuni.",
    "trend_range" to "Wigo wa wiki: KES %1\$d → KES %2\$d.",
    "board_title" to "🏪 Ubao wa masoko — %1\$s (%2\$s, %3\$s)",
    "board_hint" to "Linganisha pa kuuza leo; kijani = inapanda, nyekundu = inashuka.",
    "board_source" to "Chanzo: Ubao hai wa M-AgriLink (mtindo wa KAMIS), umeigwa nje ya mtandao.",
    "home_corridor" to "Kitovu cha Kaunti Lengwa",
    "home_tap" to "Gusa kuchagua eneo lengwa...",
    "home_dropdown" to "Mshale wa kuchagua",
    "home_crop_q" to "🌱 Ume Panda Zao Gani?",
    "home_crop_hint" to "Andika Mahindi, Maharagwe, Vitunguu, Mtama...",
    "home_corrected" to "🔍 Inaonyesha matokeo ya \"%1\$s\" (uliandika \"%2\$s\")",
    "home_recent" to "⏱ Mazao yangu ya hivi karibuni",
    "home_recent_hint" to "Gusa zao la hivi karibuni kwa mwenendo kamili wa KAMIS na uchambuzi.",
    "bp_title" to "📋 Ramani ya Uendeshaji wa Shamba Langu",
    "bp_unmute" to "Washa sauti zote",
    "bp_mute" to "Zima sauti zote",
    "lens_your_crop" to "zao lako",
    "lens_foliar" to "wadudu wa majani",
    "qual_dark" to "⚠️ Tahadhari ya Kichanganuzi: Fremu ni nyeusi sana — hakuna maelezo ya zao yanayoonekana. Safisha lenzi, washa taa, na uelekeze imara kwenye zao (jani, tunda, au shina) likijaza fremu, kisha ujaribu tena.",
    "qual_bright" to "⚠️ Tahadhari ya Kichanganuzi: Fremu imeoshwa na mwangaza. Funika zao kivuli, futa lenzi, shikilia imara na ujaribu tena.",
    "qual_blurry" to "⚠️ Tahadhari ya Kichanganuzi: Lenzi ni blur au imefunikwa — shikilia simu imara, gusa kulenga, safisha lenzi, na fanya zao lijaze fremu.",
    "qual_noleaf" to "⚠️ Tahadhari ya Kichanganuzi: Hakuna zao lililogunduliwa. Elekeza kamera kwenye jani, tunda, au shina la zao ili lijaze fremu — si chumba cheusi, ukuta, au mandharinyuma tupu.",
    "qual_lowconf" to "⚠️ Tahadhari ya Kichanganuzi: Uchanganuzi hauko wazi (uhakika mdogo %1\$d%%). Safisha lenzi, boresha mwanga, sogea karibu ili jani lijaze fremu, na ujaribu tena.",
    "qual_crash" to "⚠️ Tahadhari ya Kichanganuzi: Imeshindwa kuchambua fremu kwa sababu ya mwanga hafifu au kamera. Shikilia simu imara na ujaribu tena.",
    "arb_title" to "Matokeo ya Uchambuzi wa Faida",
    "arb_empty" to "Chagua kitovu cha biashara hapo juu ili kukokotoa faida za ndani dhidi ya mipakani, gharama za usafiri, na rekodi za ushauri.",
    "arb_route" to "Njia ya Ukanda: Baringo Nyumbani ➔ %1\$s",
    "arb_local" to "Bei ya Nyumbani: KES %1\$d",
    "arb_hub" to "Bei Lengwa Kitovuni",
    "arb_net" to "+KES %1\$d faida",
    "arb_moist_fallback" to "Kausha nafaka hadi kiwango cha 13.5% kabla ya kufunga.",
    "scan_title" to "🏥 Uchunguzi wa Magonjwa ya Mazao",
    "scan_desc" to "Piga au pakia picha yoyote ya zao — jani, tunda, au shina — kwa hatua za udhibiti za Google-AI papo hapo.",
    "scan_launch" to "Zindua Kichanganuzi cha Kamera cha AI",
    "scan_upload" to "🖼️ Pakia Picha ya Zao Badala Yake",
    "scan_point" to "Elekeza lenzi kwenye %1\$s jani au tunda…",
    "scan_crop_fallback" to "zao",
    "scan_no_image" to "⚠️ Hakuna picha iliyochaguliwa. Gusa 🖼️ Pakia Picha ya Zao na uchague picha wazi ya zao.",
    "scan_unreadable" to "⚠️ Tahadhari ya Kichanganuzi: Imeshindwa kusoma picha hiyo. Chagua picha wazi ya jani, tunda, au shina la zao na ujaribu tena.",
    "scan_decode_fail" to "⚠️ Tahadhari ya Kichanganuzi: Imeshindwa kusoma picha hiyo (%1\$s). Chagua picha wazi ya jani, tunda, au shina la zao na ujaribu tena.",
    "scan_frame_fail" to "⚠️ Tahadhari ya Kichanganuzi: Imeshindwa kuchambua fremu kwa sababu ya mwanga hafifu au kamera. Shikilia simu imara na ujaribu tena.",
    "dlg_scanner" to "Kichanganuzi cha Shamba cha Kamera cha AI",
    "scan_need_cam" to "Ruhusa ya kamera inahitajika kuchanganua majani ya mazao moja kwa moja shambani.",
    "scan_grant" to "Ruhusu Matumizi ya Kamera",
    "scan_live_lens" to "📷 Lenzi hai: %1\$s",
    "scan_conf" to "Uhakika: %1\$d%% • %2\$s",
    "scan_upload_unclear" to "⚠️ Tahadhari ya Kichanganuzi: Upakiaji huo hauko wazi — chagua picha angavu na kali ya zao (jani, tunda, au shina likijaza fremu) au pakia picha nyingine.",
    "scan_cam_unclear" to "⚠️ Tahadhari ya Kichanganuzi: Uchanganuzi hauko wazi — safisha lenzi, boresha mwanga, elekeza kwenye jani au tunda la zao likijaza fremu, na uguse tena.",
    "scan_status" to "📡 %1\$s • lenzi: %2\$s (%3\$d%%)",
    "scan_upload_another" to "🖼️ Pakia picha nyingine",
    "scan_analyzing" to "🔍 Kichambuzi cha AI: Kinachanganua majani ya mazao kutafuta hitilafu...",
    "scan_analyzing_what" to "🔍 Kichambuzi cha AI: Kinachanganua %1\$s kutafuta hitilafu...",
    "scan_what_uploaded" to "picha iliyopakiwa",
    "scan_what_leaves" to "majani na matunda ya mazao",
    "scan_tap_capture" to "Gusa duara la kunasa kuchanganua majani ya %1\$s kwa kamera ya nyuma.",
    "scan_cam_fail" to "⚠️ Kamera imeshindwa kuanza (%1\$s). Ruhusu kamera, pakia picha badala yake, au anzisha upya kichanganuzi.",
    "google_title" to "🔎 Maelezo ya Zao ya Google AI",
    "google_src" to "Chanzo: %1\$s • sehemu yoyote ya zao (jani, tunda, shina)",
    "google_pulling" to "Inaleta maelezo ya Google AI…",
    "google_empty" to "Maelezo ya Google yataonekana hapa ukiwa mtandaoni.",
    "google_open" to "🔍 Fungua Maelezo Kamili kwenye Google",
    "google_fail" to "Utafutaji wa Google umeshindwa. Angalia muunganisho na utumie vitufe hapa chini.",
    "btn_youtube" to "▶️ YouTube",
    "btn_facebook" to "📘 Facebook",
    "btn_cabi" to "Tazama wasifu kamili wa ushauri kwenye Benki ya Maarifa ya CABI Plantwise",
    "src_gallery" to "Upakiaji wa picha",
    "scan_uploaded_img" to "Picha ya zao iliyopakiwa",
    "scan_capture" to "Nasa uchanganuzi wa jani",
    "scan_close" to "Funga Uchanganuzi",
    "scan_full_prefix" to "Mechi ya lenzi hai (%1\$s): %2\$s (%3\$d%% uhakika kupitia %4\$s).",
    "scan_full_google" to "🔎 Google AI (%1\$s): %2\$s",
    "wx_rain_badge" to "🌧️ Mvua Hai Imegunduliwa kwenye Eneo Lako la GPS.",
    "wx_rain_advisory" to "☔ Ushauri wa Shamba: Manyunyu ya mvua yamethibitishwa juu ya shamba lako. Simamisha mara moja unyunyiziaji wote wa mbolea au dawa za wadudu kuepuka kuoshwa kwa mazao.",
    "pay_title" to "🔒 Malipo ya M-Pesa",
    "pay_mpesa" to "💳 Lipa kwa M-Pesa kwa Usalama",
    "pay_sending" to "Inatuma ombi salama la M-Pesa…",
    "pay_success" to "✅ Ombi la STK limetumwa kwa %1\$s kwa %2\$s. Weka PIN yako ya M-Pesa kwenye simu kukamilisha.",
    "pay_failed" to "❌ Malipo yameshindwa: %1\$s",
    "pay_noconfig" to "Malipo hayajaandaliwa — mwombe mmiliki wa programu kuongeza sifa za Daraja kwenye local.properties, kisha aunde upya.",
    "pay_badphone" to "Ongeza nambari sahihi ya M-Pesa (07…/01…) kwenye wasifu wa Akaunti yako kwanza.",
    "pay_err_timeout" to "Ombi limechelewa. Jaribu tena.",
    "pay_err_offline" to "Hakuna muunganisho wa intaneti. Unganisha na ujaribu tena.",
    "pay_err_rejected" to "Malipo yamekataliwa na Safaricom (%1\$s).",
    "logi_bags" to "Magunia ya kusafirisha",
    "logi_bags_hint" to "k.m. 10",
    "logi_estimate" to "Makadirio ya usafiri: %1\$s (magunia %2\$d × KES %3\$d).",
    "faq_title" to "❓ Maswali Yanayoulizwa Mara kwa Mara",
    "faq_q1" to "📱 Je, M-AgriLink itafanya kazi simu yangu ikiwa nje ya mtandao kabisa?",
    "faq_a1" to "Ndiyo! M-AgriLink ina ngao ya nje ya mtandao. Bei za soko za kaunti 47 za Kenya, utabiri wa hali ya hewa, na miongozo ya kilimo ya Shamba AI huhifadhiwa moja kwa moja kwenye kumbukumbu ya simu yako kupitia Hifadhidata salama ya Room.",
    "faq_q2" to "🐛 Kichanganuzi cha Mazao cha Shamba AI kiko sahihi kiasi gani?",
    "faq_a2" to "Kichanganuzi cha AI kinatumia mifumo ya vyanzo vingi inayoungwa mkono na hifadhidata rasmi za KALRO ABIRI, CABI Plantwise, na icipe. Hulinganisha hitilafu za majani na miundo thibitishwa ya kukabiliana kibiolojia na kikemikali.",
    "faq_q3" to "🗺️ Kwa nini programu inaomba ruhusa ya eneo langu?",
    "faq_a3" to "Tunatumia kuratibu za GPS za simu yako pekee kuuliza API ya Open-Meteo isiyohitaji funguo ili kukupa joto halisi la eneo lako na tahadhari za mvua za shamba lako mahususi.",
    "faq_q4" to "🐝 Jarida la Nyuki la KALRO ABIRI ni nini?",
    "faq_a4" to "Ni kifuatilia ufugaji nyuki kilichoandaliwa chini ya wasifu wa muundaji wa jukwaa lako Levis Lekesio. Kinakuongoza hatua kwa hatua kupitia mizunguko ya malisho ya koloni za kisasa za Langstroth, viwango vya unyevu, na uboreshaji wa mavuno ya asali.",
    "scan_confirm_unclear" to "⚠️ Uchanganuzi haujulikani — hakuna zao lililochukuliwa. Safisha lenzi, boresha mwanga, elekeza kwenye jani, tunda, au shina la zao likijaza fremu, na uzindue kichanganuzi tena.",
    "src_camera" to "Kamera moja kwa moja",
    "shamba_title" to "💬 Muulize Shamba AI",
    "shamba_desc" to "Andika jinsi shamba, mazao au ng'ombe wako wanavyoendelea — Shamba hujibu na ushauri wa kirafiki kwa Kiingereza au Kiswahili.",
    "shamba_start" to "Anza Gumzo",
    "lorry_title" to "🚚 Kitafuta Malori",
    "lorry_demo" to "Saraka ya majaribio — gusa Piga au WhatsApp kukodi:",
    "lorry_hide" to "Ficha Anwani za Wasafirishaji",
    "lorry_find" to "Tafuta Lori Sasa",
    "lorry_tasks" to "🧾 Kazi zangu za usafiri — fuatilia lori lako:",
    "lorry_enroute" to "🚚 Weka Njiani",
    "lorry_delivered" to "✅ Weka Imewasilishwa",
    "lorry_registered" to "✓ Malori yaliyosajiliwa na madereva:",
    "lorry_call" to "📞 Piga",
    "lorry_wa" to "💬 WhatsApp",
    "lorry_hire" to "🚜 Kodisha",
    "lorry_close_reg" to "Funga usajili wa lori",
    "lorry_open_reg" to "＋ Sajili lori langu (dereva)",
    "lorry_save" to "Hifadhi lori",
    "lorry_hint_name" to "Jina la dereva / SACCO",
    "lorry_hint_phone" to "Simu k.m. 0722000000",
    "lorry_hint_capacity" to "Uwezo k.m. 10T",
    "lorry_hint_town" to "Mji mkuu k.m. Marigat",
    "lorry_hint_route" to "Njia k.m. Marigat → Kitovu cha Nairobi",
    "sac3_title" to "💰 Mipango ya Pembejeo za SACCO",
    "sac3_sub_empty" to "Mienendo ya jumla ya mbegu na mbolea (msingi wa Baringo).",
    "sac3_sub_county" to "Mienendo ya jumla ya %1\$s — panga bajeti kabla ya kupanda.",
    "sac3_tip" to "Kidokezo cha kuweka akiba: Weka KES 250/wiki kupitia SACCO kugharamia DAP + mbegu za ekari 1 kabla ya mvua.",
    "cta_launch" to "Zindua Kichambuzi cha Ukanda wa Mikoa",
    "bp_action" to "🚜 Hatua ya Haraka:",
    "bp_harvest" to "🌾 Alama Salama ya Kuvuna:",
    "live_mgmt" to "⚠️ Ushauri Hai wa Usimamizi wa Mazao",
    "live_brief_title" to "🌐 Muhtasari Hai wa Zao: %1\$s",
    "live_searching" to "Inatafuta vyanzo hai…",
    "live_none" to "Hakuna mchoro uliopatikana wa \"%1\$s\" — jaribu Mahindi, Maharagwe, Vitunguu au Mtama.",
    "live_saved" to "Imehifadhiwa kiotomatiki kwenye mazao yangu ya hivi karibuni kwenye kifaa hiki.",
    "adv_maize_humid" to "Tahadhari ya unyevu mkubwa (72%) imegunduliwa Baringo. Hali ya shamba inaongeza hatari ya fangasi wa Gray Leaf Spot. Chunguza majani kwa ukaribu wiki hii.",
    "adv_beans_calm" to "Upepo ni shwari kwa 5.2 km/h. Dirisha zuri la asubuhi liko wazi kutumia kinga salama za mazao.",
    "adv_default" to "Joto %1\$s°C • Unyevu %2\$d%% • Upepo %3\$s km/h — chunguza mashamba ya %4\$s asubuhi na mapema; weka majani makavu kuzuia fangasi.",
    "read_aloud" to "Soma matokeo kwa sauti",
    "scan_ident" to "🩺 UTAMBUZI WA WADUDU",
    "scan_ident_healthy" to "%1\$s yako inaonekana na afya (%2\$d%% uhakika kupitia %3\$s).",
    "scan_ident_hit" to "Zao lako linakabiliwa na shambulio kubwa la %1\$s kwenye %2\$s (%3\$d%% uhakika kupitia %4\$s).",
    "scan_control" to "🛠️ UDHIBITI & USIMAMIZI WA HARAKA",
    "scan_protocol" to "🌿 ITIFAKI MAHSUSI YA ZAO",
    "scan_validated" to "✅ UDHIBITI ULIOTHIBITISHWA (KALRO • CABI • icipe • FAO)",
    "honey_live" to "🍯 BEI HAI ZA ASALI • KAMIS",
    "honey_deviations" to "📍 TOFAUTI ZA MASOKO YA NDANI",
    "honey_base" to "Wastani wa Fahirisi ya Soko: %1\$s",
    "honey_traj" to "Mwelekeo: %1\$s",
    "logi_title" to "🚚 Usafiri wa Mikoa & Malori",
    "logi_nocounty" to "Chagua kitovu cha ukanda hapo juu kwa safari za usiku wa leo.",
    "logi_route" to "Ukanda hai: %1\$s ➔ %2\$s",
    "logi_contact" to "📞 Gusa kumpigia dereva",
    "logi_line1" to "• Wasafirishaji %1\$d walioidhinishwa karibu na %2\$s kuelekea %3\$s usiku wa leo.",
    "logi_line2" to "• Gharama ya Usafiri: KES %1\$d - KES %2\$d kwa gunia la nafaka/mazao.",
    "logi_line3" to "• Hali ya Usalama: %1\$s Gusa kumpigia dereva.",
    "sac_title" to "💰 Mipango ya Pembejeo za SACCO",
    "sac_sub" to "Mienendo ya jumla iliyoidhinishwa — panga bajeti kabla ya kupanda, epuka kupandishwa bei.",
    "sac_acre" to "Ukubwa unaokadiriwa (ekari)",
    "sac_acre_hint" to "k.m. 2.5",
    "sac_proj_for" to "Makadirio ya msingi kwa ekari %1\$s:",
    "sac_seed" to "🌱 Mbegu (pakiti %1\$d): %2\$s",
    "sac_dap" to "🧪 DAP (magunia %1\$d): %2\$s",
    "sac_compost" to "🌿 Mbolea (magunia %1\$d): %2\$s",
    "sac_total" to "Jumla ya uwekezaji: %1\$s",
    "hive_title" to "🐝 Jarida la Nyuki la KALRO ABIRI",
    "hive_yield_h" to "📊 Vipimo vya Mavuno Yanayotarajiwa (Mizinga ya Kisasa ya Langstroth / KTB)",
    "hive_yield_1" to "• Lengo la Mavuno: kg 24 hadi 30 za asali ghafi kwa mzinga, huvunwa mara mbili kwa mwaka.",
    "hive_yield_2" to "• Uwekezaji wa Mzinga wa Ruzuku: KES 2,500 gharama ya kawaida ya kuanzia.",
    "hive_yield_3" to "• Faida: mizinga 10 hai huzalisha takriban KES 144,000 kwa msimu.",
    "hive_forage_h" to "🌱 Kalenda ya Malisho ya Asali ya Mikoa",
    "hive_forage_1" to "• Malisho: Hifadhi ya Migunga na vichaka vya maua mengi kwenye korido za ASAL.",
    "hive_forage_2" to "• Kinga ya Tabianchi: Dumisha joto la ndani ya mzinga wakati wa ukame mkali kuzuia kukimbia kwa koloni.",
    "hive_gallery_h" to "📸 Matunzio ya Picha za Nyuki",
    "hive_footnote" to "*Imetolewa kupitia Mnyororo wa Thamani wa Ufugaji Nyuki wa KALRO, Mwongozo wa TIMPs 2020.*",
    "art_hero" to "📰 Habari za AgriTech na Kilimo",
    "art_sub" to "Habari kuu na zinazovuma kwa wakulima wa Kenya.",
    "art_refresh" to "↻ Onyesha upya habari",
    "art_live" to "📡 MOJA KWA MOJA",
    "art_offline" to "📦 CHAGUO NJE YA MTANDAO",
    "art_loading" to "Inaleta habari kuu za agritech…",
    "art_read" to "📖 Soma habari",
    "art_video" to "▶️ Video",
    "art_sources" to "Vyanzo: Google News RSS (moja kwa moja) • FAO / icipe / CABI / KALRO (nje ya mtandao).",
    "cb_lead_1" to "Kuondoa Kimitambo:",
    "cb_rest_1" to "Ondoa wadudu kwa mkono kwa maji ya nguvu na okota vifuu vya mayai mara mbili kwa wiki.",
    "cb_lead_2" to "Kupogoa & Usafi:",
    "cb_rest_2" to "Ondoa kwa usalama sehemu za mmea zilizovamiwa kwa kupogoa majani na kuyachoma ili kuvunja mzunguko wa maisha.",
    "cb_lead_3" to "Dawa za Asili:",
    "cb_rest_3" to "Tumia itifaki za unyunyiziaji za asubuhi za mwarobaini au viuatilifu hai, ukifunika matawi na mafuta ya mwarobaini au sabuni ya wadudu nyakati za baridi.",
    "cb_lead_4" to "Udhibiti wa Kibiolojia:",
    "cb_rest_4" to "Tumia kadi za wanyama wawindaji na usimamizi wa makazi — hifadhi maadui wa asili, weka Desmodium mchanganyiko na mipaka ya mitego kukandamiza wadudu.",
    "overview_cta" to "💡 Tuboreshe: Je, unalima mazao haya kwenye bustani ndogo ya nyumbani au shamba kubwa la kibiashara? Mjulishe Shamba Al ili tupendekeze mchanganyiko wa matibabu ya kikaboni unaolingana na ukubwa wako!",
    "overview_sources" to "*Imethibitishwa kupitia Hifadhidata za Utafiti za KALRO ASAL, Benki ya Maarifa ya CABI Plantwise, na icipe Kenya.*",
    "diag_healthy_title" to "✅ UTAMBUZI: %1\$s inaonekana na afya (%2\$d%% uhakika kupitia %3\$s).",
    "diag_mango" to "🎯 UTAMBUZI: Uharibifu wa Nzi wa Maembe (Bactrocera dorsalis) umegunduliwa kwenye maganda.",
    "diag_beans" to "🎯 UTAMBUZI: Nzi wa Maharagwe (Ophiomyia phaseoli) kutoboa mashina au Vidukari vyeusi vimegunduliwa.",
    "diag_maize" to "🎯 UTAMBUZI: %1\$s imegunduliwa (%2\$d%% uhakika kupitia %3\$s) — itifaki ya Jeshi la Viwavi (Spodoptera frugiperda).",
    "diag_general" to "🎯 UTAMBUZI: Hitilafu ya jumla ya majani imegunduliwa.",
    "diag_general_crop" to "🎯 UTAMBUZI: Hitilafu ya jumla ya majani/madoa imegunduliwa kwa %1\$s",
    "body_preventive" to "🌿 UTUNZAJI WA KINGA: Endelea kuchunguza mara mbili kwa wiki, safisha magugu na takataka chini, tandaza matandazo kushika unyevu, na angalia kingo za majani baada ya usiku wa unyevu. Changanua tena zikionekana madoa, mashimo au manjano.",
    "body_mango" to "🌿 USHAURI WA USIMAMIZI: Usinyunyize dawa kali karibu na mavuno. Tundika mitego ya feromoni ya methyl eugenol kwenye mwavuli (mitego 10 kwa ekari) kunasa nzi dume. Kusanya na kuzika matunda yaliyoanguka futi 2 chini au yafunge kwenye mifuko myeusi juani kwa siku chache kunyonga viluwiluwi na kuvunja mzunguko wa wadudu.",
    "body_beans" to "🌿 USHAURI WA USIMAMIZI: Funika udongo kwenye mashina wakati wa kupalilia ili kukuza mizizi. Kwa mashambulizi makubwa ya vidukari, nyunyiza dondoo za mbegu za mwarobaini au sabuni ya potasiamu asubuhi na mapema kabla nyuki hawajaamka.",
    "body_maize_1" to "🌿 MKAKATI WA KIBIOLOJIA WA KUSUKUMA-KUVUTA (icipe Kenya): Changanya safu za mahindi na Desmodium (hufukuza nondo kwa kemikali) na panda Nyasi za Napier au Brachiaria pembezoni mwa shamba kama zao la mtego. Njia hii hupunguza wadudu kwa zaidi ya 70% kiasili.",
    "body_maize_2" to "🐛 UCHUNGUZI NA TIBA ZA KITAMADUNI (CABI Plantwise): Chunguza shamba mara mbili kwa wiki. Okota na uangamize vifuu vya mayai au viwavi mara moja. Kuponda viwavi kwenye majani huzuia vizazi vijavyo.",
    "body_maize_3" to "🧪 HATUA YA DHARURA YA KEMIKALI (CIMMYT & FAO): Uharibifu ukizidi kiwango cha 20% kwenye mashina machanga, tumia dawa zilizosajiliwa kama Spinetoram au Spinosad moja kwa moja kwenye majani. Badilisha aina za kemikali kuzuia usugu.",
    "body_general" to "🌿 USHAURI WA USIMAMIZI: Weka nafasi sahihi kati ya mistari ili hewa ipite na kupunguza unyevu wa majani. Pogoa majani ya chini yaliyoambukizwa mara moja. Epuka kumwagilia juu jioni za baridi ili kuzuia kuenea kwa fangasi.",
    "out_empty" to "Chagua kaunti ili kufungua faida za ukanda, upimaji wa mazao bora, na ishara za kuuza/kusubiri.",
    "out_main" to "Hali ya ukanda wa %1\$s: mazao %2\$d yanafuatiliwa. Faida bora: %3\$s (+KES %4\$d faida). Wastani wa faida: %5\$sKES %6\$d/gunia baada ya usafiri KES 350. %7\$s",
    "out_good" to "Soko linawapendelea wauzaji — kusanya na usafirishe wiki hii.",
    "out_tight" to "Soko limebana — uza zao lililoongoza pekee au kusanya na majirani.",
    "out_your_county" to "kaunti yako",
    "honey_name" to "🐝 Asali Safi ya Asili",
    "honey_bulk_lead" to "Wauzaji wa Jumla:",
    "honey_corr_lead" to "Korido Maarufu za Uzalishaji:",
    "honey_base_val" to "KES 970.00 / Kilogramu",
    "honey_traj_val" to "📈 +4.3% (+KES 40.00) Mwelekeo Unaopanda",
    "honey_bulk_val" to "KES 700.00 / Kg (Mapipa ya 20L/25L ya Jumla)",
    "honey_corr_val" to "KES 750.00 – KES 850.00 / Chupa ya 1Kg (Vipimo vya Baringo Koriema Packers na Makueni Acacia)",
    "honey_footnote" to "*Imetolewa kutoka Mfumo Rasmi wa Taarifa za Masoko ya Kilimo Kenya (KAMIS).*",
    "trans_empty" to "Wasafirishaji 3 karibu na Marigat tayari kwa safari hadi Kitovu cha Nairobi",
    "trans_fmt" to "Wasafirishaji %1\$d karibu na %2\$s tayari kwa safari hadi Kitovu cha Nairobi kuanzia KES %3\$d/tani",
    "lorry_you" to "eneo lako",
    "lorry_security" to "Korido ziko salama.",
    "input_maize" to "Mbegu za Mahindi (2kg)",
    "input_dap" to "Mbolea ya DAP (50kg)",
    "input_can" to "Mbolea ya CAN (50kg)",
    "unit_pack2kg" to "pakiti ya 2kg",
    "unit_bag50kg" to "gunia la 50kg",
    "sac_item_dap" to "Mbolea ya DAP Iliyoaidhinishwa",
    "sac_item_dap_spec" to "Gunia la 50Kg",
    "sac_item_dap_badge" to "Kiwango cha SACCO (Ruzuku)",
    "sac_item_seed" to "Mbegu za Mahindi Zilizoaidhinishwa",
    "sac_item_seed_spec" to "Pakiti ya 2Kg - H614",
    "sac_item_compost" to "Mbolea ya Asili / Bio-fertilizer",
    "sac_item_compost_spec" to "Gunia la 50Kg",
    "rem_cat_cultural" to "💡 Tiba ya Kitamaduni",
    "rem_cat_eco" to "🌱 Mkakati wa Kiikolojia",
    "rem_cat_chem" to "🧪 Hatua Salama ya Kemikali",
    "rem_mango_cultural" to "Tundika mitego ya feromoni ya methyl eugenol kwenye mwavuli (10 kwa ekari). Kusanya na kuzika matunda yaliyoanguka futi 2 chini au yafunge kwenye mifuko myeusi juani kunyonga viluwiluwi. Okota na ponda vifuu vya mayai mara mbili kwa wiki.",
    "rem_mango_eco" to "Tumia njia ya Kusukuma-Kuvuta kwa kupanda Desmodium mchanganyiko kufukuza nondo kiasili. Safisha chini ya bustani na hifadhi siafu wafumaji kama wanyama wawindaji wa nzi.",
    "rem_mango_chem" to "Ufuatiliaji ukizidi kiwango cha 20%, tumia dawa zilizosajiliwa kama Emamectin Benzoate moja kwa moja kwenye mmea. Usinyunyize sana karibu na mavuno.",
    "rem_beans_cultural" to "Funika udongo kwenye mashina wakati wa kupalilia ili kukuza mizizi. Okota na ponda vifuu vya mayai mara mbili kwa wiki.",
    "rem_beans_eco" to "Tumia njia ya Kusukuma-Kuvuta kwa kupanda Desmodium mchanganyiko. Nyunyiza dondoo za mbegu za mwarobaini au sabuni ya potasiamu asubuhi kabla nyuki hawajaamka.",
    "rem_beans_chem" to "Ufuatiliaji ukizidi kiwango cha 20%, tumia dawa zilizosajiliwa kama Emamectin Benzoate moja kwa moja kwenye mmea.",
    "rem_maize_cultural" to "Okota na ponda vifuu vya mayai mara mbili kwa wiki. Chunguza majani mara mbili kwa wiki na ponda viwavi moja kwa moja.",
    "rem_maize_eco" to "Tumia njia ya Kusukuma-Kuvuta kwa kupanda Desmodium mchanganyiko. Panda Napier/Brachiaria pembezoni kupunguza wadudu kwa zaidi ya 70%.",
    "rem_maize_chem" to "Ufuatiliaji ukizidi kiwango cha 20%, tumia dawa zilizosajiliwa kama Emamectin Benzoate moja kwa moja kwenye mmea. Badilisha aina za kemikali kuzuia usugu.",
    "rem_general_cultural" to "Pogoa majani ya chini yaliyoambukizwa mara moja na uyachome. Okota na ponda vifuu vya mayai mara mbili kwa wiki.",
    "rem_general_eco" to "Tumia njia ya Kusukuma-Kuvuta kwa kupanda Desmodium mchanganyiko. Weka nafasi ya kutosha na epuka kumwagilia juu jioni.",
    "rem_general_chem" to "Ufuatiliaji ukizidi kiwango cha 20%, tumia dawa zilizosajiliwa kama Emamectin Benzoate moja kwa moja kwenye mmea.",
    "adv_moisture" to "Kiwango salama cha unyevu cha 13.5% (KALRO). Kausha nafaka hadi ≤13.5% kabla ya kufunga kuzuia aflatoxin/ukungu.",
    "adv_maize_land" to "Maandalizi ya Shamba KALRO (Mahindi): Lima kwa kina sm 20-25 mvua zinapoanza, fyeka laini. Weka samadi tani 10/ha + DAP kg 60/ha wakati wa kupanda.",
    "adv_maize_space" to "Nafasi za Kupanda (Mahindi): sm 75 x 25, mbegu 1 kwa shimo (mimea ~53,000/ha). Punguza hadi mche mmoja imara.",
    "adv_maize_harvest" to "Vuna maganda yanapogeuka kahawia na punje kuwa ngumu. Pura na kausha kwenye turubali hadi unyevu 13.5% kabla ya kuhifadhi kwenye magunia yasiyopitisha hewa.",
    "adv_beans_land" to "Maandalizi ya Shamba KALRO (Maharagwe): Lima sm 15-20, kitanda laini imara. Chanja mbegu na rhizobium. Weka TSP kg 40/ha wakati wa kupanda; epuka naitrojeni nyingi.",
    "adv_beans_space" to "Nafasi za Kupanda (Maharagwe): sm 45 x 10, mbegu 1 kwa shimo (mimea ~220,000/ha). Panda sm 3-5 chini.",
    "adv_beans_harvest" to "Vuna maganda 90% yanapokauka/njano. Pura haraka na kausha maharagwe hadi kiwango cha 13.5% kabla ya kufunga.",
    "adv_onions_land" to "Maandalizi ya Shamba KALRO (Vitunguu): Panda kitalu mita 1 upana, tifutifu inayopitisha maji pH 6.0-7.0. Hamisha miche ya wiki 6-8 kwenye shamba lililolimwa kwa kina (sm 20), tambarare na samadi tani 8/ha.",
    "adv_onions_space" to "Nafasi za Kupanda (Vitunguu): sm 30 x 10 shambani (mimea ~330,000/ha). Tandaza matandazo na mwagilia kidogo mara mbili kwa wiki.",
    "adv_onions_harvest" to "Vuna asilimia 70 ya vilele vinapoanguka. Kausha vitunguu siku 7-10 kivulini hadi maganda ya nje yakauke kabla ya kupanga.",
    "adv_sorghum_land" to "Maandalizi ya Shamba KALRO (Mtama): Kilimo kidogo / lima sm 15-20. Hustahimili ukame; weka CAN kg 40/ha juu shina linapofikia goti. Dhibiti visumbya kwa kubadilisha na mikunde.",
    "adv_sorghum_space" to "Nafasi za Kupanda (Mtama): sm 75 x 20, mbegu 2 kwa shimo punguza hadi 1 (mimea ~66,000/ha).",
    "adv_sorghum_harvest" to "Vuna suke nafaka inapokuwa ngumu na <13.5% unyevu. Pura, pepeta na kausha zaidi hadi kiwango cha 13.5% kwa hifadhi salama.",
    "adv_custom_land" to "Maandalizi ya Shamba KALRO (%1\$s): Andaa kitanda kirefu kinachopitisha maji mvua zinapoanza. Weka samadi iliyooza + mbolea ya msingi kwa kipimo cha udongo.",
    "adv_custom_space" to "Nafasi za Kupanda (%1\$s): Weka nafasi ya mwavuli kamili kwa mwongozo wa safu wa KALRO; tandaza matandazo kushika unyevu.",
    "adv_custom_harvest" to "Vuna %1\$s ukikomaa kabisa na kausha hadi kiwango salama cha 13.5% kabla ya kuhifadhi au kuuza."
)

/** Plain lookup (safe in non-composable code): Kiswahili → fallback English → key. */
fun tr(key: String): String {
    if (AppLocale.isSwahili) SW[key]?.let { return it }
    return EN[key] ?: key
}

/** Formatted lookup with %1$s-style args. */
fun trf(key: String, vararg args: Any?): String {
    return try {
        String.format(Locale.US, tr(key), *args)
    } catch (e: Exception) {
        tr(key)
    }
}

/** Reactive lookup for composables: recomposes on language switch. */
@Composable
fun str(key: String): String {
    AppLocale.language
    return tr(key)
}

/** Reactive formatted lookup for composables. */
@Composable
fun strf(key: String, vararg args: Any?): String {
    AppLocale.language
    return trf(key, *args)
}
